### ISSUE TITLE
Show all commands we're running even without `--with-output` flag?

### ISSUE THREAD

**Issue by mattstauffer** [tighten/lambo#126]
![image](https://user-images.githubusercontent.com/151829/93656830-48b2b400-f9fb-11ea-8130-5533c1c1d35e.png)

When anything takes a long time (e.g. Installing the UI scaffolding, Installing node dependencies, etc.) it feels kinda like.. I want MORE info.

I wonder if we have all the commands that are running, but maybe `> commandhere` indented like the Laravel installer does?

**Comment by jonsugar** [comment]
Yep. Makes sense. So the default output should be similar to that of `lambo new foo -v` which does what you suggest (with a little extra output).  

What do you think about:

- `lambo new foo` as you suggest above image plus commands only (as you suggest).
- `lambo new foo -v` stays the same (your preferred output plus a few extras).
- `lambo new foo -vv` everything above and also shows command output (` we remove the --with-output option)`
- `lambo new foo -vvv` everything above and also shows debug output.

**Comment by mattstauffer** [comment]
@jonsugar yes I love that
