### ISSUE TITLE
Issues opening in VS Code in beta

### ISSUE THREAD

**Issue by mattstauffer** [tighten/lambo#127]
![image](https://user-images.githubusercontent.com/151829/93656985-88c66680-f9fc-11ea-9ff7-c7bf2d9992f0.png)

**Comment by jonsugar** [comment]
Hmmm. I can't reproduce. Can you tell me how you got this?

**Comment by mattstauffer** [comment]
> It's easier all around just to open the editor at the end and handle any error that occurs then. Thoughts?

I think in the shell version we opened all editors *except* terminal editors early (so you can start coding while npm installs). How hard would that be?

> Hmmm, I can't reproduce. Can you tell me how you got this?

let me try it again and see 😆

**Comment by mattstauffer** [comment]
Can't repro. 🤷🏻‍♂️
