### ISSUE TITLE
Investigate what can be done about the Laravel Installer failing when it is used with --quiet.

### ISSUE THREAD

**Issue by mattstauffer** [tighten/lambo#130]
Issue created by @jonsugar, I just converted it from a note to an issue.

From Jon:
> TL;DR its because it blindly passes the --quiet / --no-ansi flag through to all commands that are run. chmod does not have these options and interprets them as directories.

**Comment by mattstauffer** [comment]
OK, so.. I'm not getting that error when I pass it in on the command line:

![image](https://user-images.githubusercontent.com/151829/93657675-8404b100-fa02-11ea-8f83-4120b91f5212.png)

Is this something they fixed? Or something only we are triggering?

**Comment by jonsugar** [comment]
Are you buy any chance using the ^3.0 version of the laravel installer? I just tested with 3.2.0 and reproduced your experience. Switch to ^4.0 (4.0.4) and:

![Screenshot 2020-09-19 at 16 14 07](https://user-images.githubusercontent.com/1974648/93670424-31bfa080-fa93-11ea-9297-57cf9f1d7b28.png)

**Comment by jonsugar** [comment]
Fixed in https://github.com/laravel/installer/pull/156
