### ISSUE TITLE
Add support for Laravel Breeze

### ISSUE THREAD

**Issue by jonsugar** [tighten/lambo#151]
### API additions

Create a new Laravel application with the Breeze starter-kit:

```sh
# Use Blade templating.
lambo new my-app --breeze
lambo new my-app --breeze=blade

# Use InertiaJS + Vue templating.
lambo new my-app --breeze=vue

# Use InertiaJS +  React templating.
lambo new my-app --breeze=react
```

### API Changes

Currently, the options for using Jetstream are `--inertia`, `--livewire` and `--teams` but this causes confusion when considering Breeze plus Inertia. 

The Jetstream API will change as follows:

```sh
lambo new my-app --jetstream=inertia
lambo new my-app --jetstream=livewire
lambo new my-app --jetstream=inertia,teams
lambo new my-app --jetstream=livewire,teams
```

### References

- [the Laravel Breeze documentation](https://laravel.com/docs/8.x/starter-kits#laravel-breeze)

**Comment by MACscr** [comment]
Cant wait for breeze support. Dont even need inertia or other support. =P

**Comment by mattstauffer** [comment]
@jonsugar Hm, i agree, with breeze it needs to be `--jetstream=`.
