### ISSUE TITLE
Remove site option?

### ISSUE THREAD

**Issue by MACscr** [tighten/lambo#155]
I love lambo and use it to quickly spin up sites for dev/testing. Its super complimentary to valet and love that the editor and after install action options. Anyway, i dont see the option, but would love a remove site option that deleted the site and removed the associated database. Not a huge deal, but i think it would be handy.

**Comment by mattstauffer** [comment]
Thanks @MACscr! I *think* for now I'll just keep it to spinning up only, but thanks for the kind words and the idea!
