### ISSUE TITLE
Support for Vite

### ISSUE THREAD

**Issue by SimonBarrettACT** [tighten/lambo#174]
Since the move to building assets with Vite the build hangs on the last of the following lines:

```
 // Installing Laravel Breeze starter kit

  EXEC  cd /Users/simon/Sites/snippets && composer require laravel/breeze --dev --quiet
  EXEC  cd /Users/simon/Sites/snippets && php artisan breeze:install --quiet
  EXEC  cd /Users/simon/Sites/snippets && npm install --silent
  EXEC  cd /Users/simon/Sites/snippets && npm run dev --silent


```

**Comment by jonsugar** [comment]
Thanks for the heads-up @SimonBarrettACT. Lambo should play nicely with Vite now. 

You may need to run `composer global require tightenco/lambo:^3.0` to force update to the new version.
