### ISSUE TITLE
$PROJECTPATH environment variable is not set correctly when running the after script

### ISSUE THREAD

**Issue by camya** [tighten/lambo#180]
I **try to copy files** from the includes folder to my project. (Via after script, lambo edit-after)

`cp -R ~/.lambo/includes/ $PROJECTPATH`

This **does not work** at all for me (Apple Mac M1) and I can't debug it because I don't have any error output. I'm not sure if this is a problem with the `$PROJECTPATH` variable.

Otherwise the "after script" works fine. Composer packages are installed like intended.

Maybe it's possible to log the output / errors of the "after script" to a debug file? 

Example: `~/.lambo/logs/after.log` 

Here is an example of a file:

`cp -R ~/.lambo/includes/resources/views/layouts/app.blade.php ${PROJECTPATH}/resources/views/layouts/app.blade.php`

**Comment by jonsugar** [comment]
@camya this should be fixed now. Let me know if there is still a problem. 

I also updated the installation command as you suggested.

**Comment by camya** [comment]
The fix works perfect. Just created a new project and all commands where executed. Thank you for you quick update.
